### ISSUE TITLE
strategies for reducing attrition/low-quality data

### ISSUE THREAD

**Issue by judithfan** [cogtoolslab/compositional-abstractions#20]
## task 
- [x] include a block placing practice trial before they get paired up. if they fail the practice trial N times, terminate HIT & pay a base comp. of how long it takes to read the instructions.  @wpmccarthy 
- [x] after they get paired up, have a limit on the number of times they can do the practice trial before HIT terminates & they're given base comp. @choldawa 

- [x] change to 8 out of 8 blocks placed
- [ ] fail.html page with 'press this button to get your base pay' (Instead of current fail.html)
- [x] fail after interactive game.end()
- [x] send data from solo practice
- [x] check: 3 strikes on the paired practice trial
- [ ] change text to flow when progressing to paired practice trial (from individual)
- [ ] stop refresh of paired practice trial when someone leaves page

## recruitment
- [ ] try Prolific?
- [ ] try SONA?
