### ISSUE TITLE
make prototype TODOs

### ISSUE THREAD

**Issue by judithfan** [cogtoolslab/compositional-abstractions#6]
### Remaining from 5/8/20 meeting

- [x] @hawkrobe : add practice trial
- [x] @choldawa: embed instructions images 
- [x] @judithfan: pass through instructions text 
- [x] @hawkrobe : prevent newTrial pause on first trial after waiting room?
- [x]  @judithfan : emit question mark if button pressed with no new blocks placed
- [x] @wpmccarthy : include computed F1 score in `endTrial` event. also show in feedback message?
- [x] @hawkrobe: show text message accompanying feedback (e.g. "nice work -- here's what the tower *actually* looked like" for builder and "nice work -- here's your score!" for architect)
- [x] @hawkrobe : some prettifying of UI
- [x] @wpmccarthy : more prettifying of UI 
- [x] @choldawa : some notification of it being your turn
- [x] @choldawa : 60s (?) countdown timer for both architect and builder turns -- separate params for each role 
- [x] @hawkrobe : if participants fail practice trial, they repeat it until they achieve 100%  (need scoring data)
- [x] @hawkrobe : check that if one disconnects the other is advanced to the exit survey
- [x] @hawkrobe : make sure game ends properly after going through all trials...
- [x] @wpmccarthy / @judithfan : Decide bonus thresholds and amounts
- [x] @wpmccarthy / @judithfan : Report a score as well as bonus? 
    - [x] Instant bonus feedback?
- [ ] @wpmccarthy fix off-screen block placement

### Minor UI tweaks
- [ ] @hawkrobe : investigate random disconnections after browser tab inactive
- [ ] @wpmccarthy : adversarial testing of where blocks are legal to place (e.g. first build vertical tower; the UI then shows ghost block lower than it should, although it is correctly preventing invalid placements)
- [x] allow "done" button to be greyed out when disabled
- [x] make 'feedback' div above canvas appear as separate (white) box on top of yellow background
- [x] make 'messages' div on left side appear as separate (white/grey) box on top of yellow background
- [x] lengthen 'messages' div on left side for builder
- [x] reduce size of text at bottom

#### Compressed todo's from 4/10/20 meeting: 
1. generate `displays.js`-- @choldawa 
2. enable multi-trial experiment -- @hawkrobe 
3. other task interface enhancements & scoring -- @wpmccarthy 
4. data i/o (making sure that we're saving all the things we want) -- @jefan, but actually @hawkrobe 

--------
### Task interface
- [x] @wpmccarthy remove Matter.js and replace with pure gridworld
   - [x] display primitive block menu to speaker
   - [x] simplify environment (10x10?)
   - [x] add tick marks in center of each hemifield
   - [x] @wpmccarthy switch to colored dominoes (2x1 and 1x2)
   - [x] prevent block placement through discrete block map
   - [x] different/ better block sending (colored, different place?)
      - [x] sequence of blocks that were placed
- [x] @hawkrobe ‘waiting for partner’ landing screen until second person connects
- [x] @hawkrobe enable multi-trial sequence 
    - [x] bug: trial NaN/24
- [x] reset 'ghost' block outlines (and chat history?) at end of round @wpmccarthy 
- [x] character limit for speaker (100 characters?) @choldawa / backup: @hawkrobe 
- [x] animation for when partner is building/typing @choldawa / backup: @hawkrobe 
- [x] link up block counter, increment "X/8 blocks placed" in UI @choldawa 
- [x] remove "done with round" and send "endTrial" event to advance round after hitting 8/8 blocks 
 @choldawa 
- [x] feedback, I: show builder the target after trial ends as a "ghost" overlaid on their construction
- [x] write instructions @choldawa / @judithfan

### Stimuli 
- [x] @choldawa curate composite structures consisting of ~4 dominoes (currently static, hard-coded)
   - [x] make these randomized between trials?

### Data I/O
- [x] load in new structures
- [x] store data?
- [x] ~identify CSS source (why is bootstrap not doing anything?)~
    - [x] fix snapping for ghosts and blocks
    - [x] put display beside chat window instead of below it
    - [x] left-align text in chat log
    - [x] ‘disable’/grey out speaker send button when it’s not your turn instead of pop-up 
    - [x] ~deal with blocks falling~
- [x] pull in latest block construction client-side code
    - [x] everything is shifted up by 2 squares?
    - [x] add event handlers for Reset buttons 
    - [x] add event handler for DONE button
    - [x] Move DONE button to speaker
    - [x] remove reset button?
- [x] create logic for turn taking
    - [x] event handler to prevent chat 
    - [x] lock chat bar
    - [x] prevent from building when partner is typing
    - [x] listener sends ghost block outline of game state to speaker
- [x] pull in latest chatbox reference-game client-side code
    - [x] chatbox isn't working (probably event in customClient attached to old html element)

###  Server-side
- [x] pull in boilerplate server-side code
